export const courses = [
  {
    courseName: "Web And Mobile App Development",
    Batch: 11,
    City: "Karachi",
    RollNo: 185006,
    status : "enrolled" ,
    id: 1,
  },
  {
    courseName: "Graphic Designing",
    Batch: 12,
    City: "Lahore",
    RollNo: 185007,
    status : "pending" ,
    id: 2,
  },
  {
    courseName: "Digital Marketing",
    Batch: 10,
    City: "Islamabad",
    RollNo: 185008,
    status : "pending" ,
    id: 3,
  },
  {
    courseName: "Cybersecurity",
    Batch: 9,
    City: "Karachi",
    RollNo: 185009,
    status : "enrolled" ,
    id: 4,
  },
  {
    courseName: "Artificial Intelligence",
    Batch: 8,
    City: "Peshawar",
    RollNo: 185010,
    status : "enrolled" ,
    id: 5,
  },
  {
    courseName: "Data Science",
    Batch: 11,
    City: "Lahore",
    RollNo: 185011,
    status : "pending" ,
    id: 6,
  },
  {
    courseName: "Full Stack Development",
    Batch: 12,
    City: "Karachi",
    RollNo: 185012,
    status : "enrolled" ,
    id: 7,
  },
  {
    courseName: "UI/UX Design",
    Batch: 10,
    City: "Islamabad",
    RollNo: 185013,
    status : "enrolled" ,
    id: 8,
  },
  {
    courseName: "Game Development",
    Batch: 9,
    City: "Quetta",
    RollNo: 185014,
    status : "pending" ,
    id: 9,
  },
  {
    courseName: "Cloud Computing",
    Batch: 12,
    City: "Karachi",
    RollNo: 185015,
    status : "pending" ,
    id: 10,
  },
];
